EC2 Deploy script
Refactor (#7)

* Resource owner permission

* Filters to DRF

* Missing _api suffix

* Django utils timedelta

* Separate services fo consultations

* Force key word service arguments

* Separated selectors for consultations

* Consultations tests rename

* Export service error messages

* CheckConstraint constraint to condition

* ServiceSelectors to functions

* EmailService methods to functions

* Exception rename

* Comment status for email

* Categorization service methods to functions

* Categorization Rename api modules

* CategorizationSelectors methods to functions

* Add application error handler

* Remove final typing

* EmailService force key word arguments

* Move user list tests

* User service class vars

* Email timeout to service var

* url_generate to public method

* ID signing do service layer

* UserService error msg vars

* TagService error msg to vars

* Test database access

* Zoom integration rename

Deploy v2

Deploy v3

Example change

Deploy v4

Check ec2 secrets

Check ec2 secrets v2

Check ec2 secrets v3

Parametrize repo path

Test dry run

Clean existing containers

Run deploy compose

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -34,3 +34,52 @@ jobs:
     - name: Run tests
       run: |
         pytest
+
+  check-secrets:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - name: Check if secrets exist
+        run: |
+          if [ -z "${{ secrets.AWS_HOST_USER }}" ]; then
+            echo "Error: AWS_HOST_USER secret is not set."
+            exit 1
+          fi
+          if [ -z "${{ secrets.AWS_EC2_IP_ADDRESS }}" ]; then
+            echo "Error: AWS_EC2_IP_ADDRESS secret is not set."
+            exit 1
+          fi
+          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
+            echo "Error: EC2_SSH_KEY secret is not set."
+            exit 1
+          fi
+          echo "All required secrets are set."
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: check-secrets
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Create SSH key file
+        env:
+          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
+        run: |
+          echo "${EC2_SSH_KEY}" > ec2_key.pem
+          chmod 600 ec2_key.pem
+
+      - name: Run Deployment Script
+        env:
+          AWS_HOST_USER: ${{ secrets.AWS_HOST_USER }}
+          AWS_EC2_IP_ADDRESS: ${{ secrets.AWS_EC2_IP_ADDRESS }}
+          REPO_NAME: ${{ github.event.repository.name }}
+          DRY_RUN : false
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $AWS_HOST_USER@$AWS_EC2_IP_ADDRESS 'bash -s' < deploy_script.sh $DRY_RUN $REPO_NAME $AWS_HOST_USER
+
+      - name: Clean up SSH key file
+        run: |
+          rm ec2_key.pem
